### ISSUE TITLE
Graph Transformer

### ISSUE THREAD

**Issue by wenjun90** [liushunyu/PAC#1]
Hi @liushunyu,
请问这里是否可以集成“Graph Transformer”或者使用“Attention”？
谢谢

**Comment by liushunyu** [comment]
你好，我们的代码是基于 [stable-baseline3](https://github.com/DLR-RM/stable-baselines3) 实现的，理论上是可以集成任意网络架构进去，但由于 stable-baseline3 太厚重了，改起来比较麻烦，建议找个轻量级代码实现一个。

**Comment by wenjun90** [comment]
@liushunyu  那么我们可以制作一个Graph Transformer来从“电力观察”网格中提取特征吗？

**Comment by liushunyu** [comment]
> @liushunyu 那么我们可以制作一个Graph Transformer来从“电力观察”网格中提取特征吗？

可以吖，应该有不少论文已经这样做了
